const EVENT_ICONS = {
  INTRUSION_ATTEMPT: '⚠',
  BRUTE_FORCE: '🔐',
  MALWARE_DETECTED: '☣',
  MALWARE_DOWNLOAD: '☣',
  SUSPICIOUS_LOGIN: '👤',
  SUSPICIOUS_CONNECTION: '🔌',
  DATA_EXFILTRATION: '📤',
  PORT_SCAN: '🔍',
  PRIVILEGE_ESCALATION: '⬆',
  C2_COMMUNICATION: '📡',
  POLICY_VIOLATION: '📋',
  ANOMALOUS_TRAFFIC: '📊',
  ANOMALOUS_ACTIVITY: '📊',
  UNAUTHORIZED_ACCESS: '🚫',
  MALICIOUS_COMMAND: '⌘',
  WEB_ATTACK: '🌐',
  SQL_INJECTION: '🗄',
  XSS_ATTEMPT: '✉',
  PHISHING_DETECTED: '🎣',
};

export function iconFor(type) {
  return EVENT_ICONS[type] || '•';
}
