export const PLAYBOOKS = [
  {
    id: 'pb-001',
    name: 'Brute Force Response',
    description: 'Automated response to brute force authentication attempts',
    trigger: 'BRUTE_FORCE',
    severity: ['high', 'critical'],
    steps: [
      { id: 1, name: 'Block Source IP', action: 'firewall_block', timeout: 30, status: 'pending' },
      {
        id: 2,
        name: 'Enrich with Threat Intel',
        action: 'sentinelforge_lookup',
        timeout: 60,
        status: 'pending',
      },
      { id: 3, name: 'Capture Forensics', action: 'collect_logs', timeout: 120, status: 'pending' },
      { id: 4, name: 'Notify SOC Team', action: 'send_alert', timeout: 30, status: 'pending' },
      { id: 5, name: 'Create Ticket', action: 'create_incident', timeout: 30, status: 'pending' },
    ],
    enabled: true,
    executions: 147,
    avgTime: '2m 34s',
    successRate: 98.2,
  },
  {
    id: 'pb-002',
    name: 'Malware Containment',
    description: 'Isolate infected endpoint and initiate remediation',
    trigger: 'MALWARE_DETECTED',
    severity: ['critical'],
    steps: [
      { id: 1, name: 'Isolate Endpoint', action: 'edr_isolate', timeout: 15, status: 'pending' },
      {
        id: 2,
        name: 'Kill Malicious Process',
        action: 'edr_kill_process',
        timeout: 30,
        status: 'pending',
      },
      {
        id: 3,
        name: 'Collect Memory Dump',
        action: 'forensics_memdump',
        timeout: 300,
        status: 'pending',
      },
      { id: 4, name: 'Scan for IOCs', action: 'ioc_scan', timeout: 180, status: 'pending' },
      { id: 5, name: 'Quarantine Files', action: 'quarantine', timeout: 60, status: 'pending' },
      { id: 6, name: 'Escalate to Tier 2', action: 'escalate', timeout: 30, status: 'pending' },
    ],
    enabled: true,
    executions: 23,
    avgTime: '8m 12s',
    successRate: 95.7,
  },
  {
    id: 'pb-003',
    name: 'Data Exfiltration Response',
    description: 'Respond to potential data exfiltration attempts',
    trigger: 'DATA_EXFILTRATION',
    severity: ['critical'],
    steps: [
      {
        id: 1,
        name: 'Block Destination',
        action: 'firewall_block_dest',
        timeout: 15,
        status: 'pending',
      },
      {
        id: 2,
        name: 'Terminate Connection',
        action: 'kill_connection',
        timeout: 10,
        status: 'pending',
      },
      {
        id: 3,
        name: 'Capture Network Traffic',
        action: 'pcap_capture',
        timeout: 60,
        status: 'pending',
      },
      { id: 4, name: 'Identify Data Scope', action: 'dlp_scan', timeout: 300, status: 'pending' },
      {
        id: 5,
        name: 'Preserve Evidence',
        action: 'evidence_collection',
        timeout: 120,
        status: 'pending',
      },
      {
        id: 6,
        name: 'Executive Notification',
        action: 'exec_alert',
        timeout: 30,
        status: 'pending',
      },
      { id: 7, name: 'Legal Hold', action: 'legal_hold', timeout: 60, status: 'pending' },
    ],
    enabled: true,
    executions: 8,
    avgTime: '12m 45s',
    successRate: 100,
  },
  {
    id: 'pb-004',
    name: 'C2 Communication Block',
    description: 'Detect and block command and control communications',
    trigger: 'C2_COMMUNICATION',
    severity: ['critical', 'high'],
    steps: [
      { id: 1, name: 'Block C2 Domain/IP', action: 'dns_sinkhole', timeout: 15, status: 'pending' },
      {
        id: 2,
        name: 'Isolate Affected Host',
        action: 'edr_isolate',
        timeout: 30,
        status: 'pending',
      },
      {
        id: 3,
        name: 'Hunt for Persistence',
        action: 'persistence_scan',
        timeout: 180,
        status: 'pending',
      },
      {
        id: 4,
        name: 'Update Threat Intel',
        action: 'sentinelforge_update',
        timeout: 30,
        status: 'pending',
      },
      {
        id: 5,
        name: 'Network-wide Scan',
        action: 'network_ioc_scan',
        timeout: 600,
        status: 'pending',
      },
    ],
    enabled: true,
    executions: 34,
    avgTime: '15m 22s',
    successRate: 97.1,
  },
  {
    id: 'pb-005',
    name: 'Phishing Response',
    description: 'Handle reported phishing emails and compromised accounts',
    trigger: 'PHISHING_DETECTED',
    severity: ['medium', 'high'],
    steps: [
      {
        id: 1,
        name: 'Quarantine Email',
        action: 'email_quarantine',
        timeout: 30,
        status: 'pending',
      },
      { id: 2, name: 'Extract IOCs', action: 'email_ioc_extract', timeout: 60, status: 'pending' },
      {
        id: 3,
        name: 'Block Sender Domain',
        action: 'email_block_domain',
        timeout: 30,
        status: 'pending',
      },
      { id: 4, name: 'Search Mailboxes', action: 'email_search', timeout: 300, status: 'pending' },
      {
        id: 5,
        name: 'Reset Credentials',
        action: 'password_reset',
        timeout: 60,
        status: 'pending',
      },
      { id: 6, name: 'User Notification', action: 'user_notify', timeout: 30, status: 'pending' },
    ],
    enabled: false,
    executions: 89,
    avgTime: '5m 18s',
    successRate: 99.1,
  },
  {
    id: 'pb-006',
    name: 'Privilege Escalation',
    description: 'Respond to unauthorized privilege escalation attempts',
    trigger: 'PRIVILEGE_ESCALATION',
    severity: ['high', 'critical'],
    steps: [
      { id: 1, name: 'Disable Account', action: 'disable_account', timeout: 15, status: 'pending' },
      { id: 2, name: 'Revoke Sessions', action: 'revoke_sessions', timeout: 30, status: 'pending' },
      { id: 3, name: 'Audit Access Logs', action: 'access_audit', timeout: 180, status: 'pending' },
      {
        id: 4,
        name: 'Check for Lateral Movement',
        action: 'lateral_scan',
        timeout: 300,
        status: 'pending',
      },
      {
        id: 5,
        name: 'Manager Notification',
        action: 'manager_alert',
        timeout: 30,
        status: 'pending',
      },
    ],
    enabled: true,
    executions: 56,
    avgTime: '6m 42s',
    successRate: 96.4,
  },
];

export const MANUAL_PLAYBOOK = {
  id: 'pb-manual',
  name: 'Manual Investigation',
  description: 'Analyst-started investigation when no automated playbook matches',
  trigger: '*',
  severity: ['low', 'medium', 'high', 'critical'],
  steps: [
    {
      id: 1,
      name: 'Enrich with Threat Intel',
      action: 'sentinelforge_lookup',
      timeout: 60,
      status: 'pending',
    },
    { id: 2, name: 'Capture Forensics', action: 'collect_logs', timeout: 120, status: 'pending' },
    { id: 3, name: 'Notify SOC Team', action: 'send_alert', timeout: 30, status: 'pending' },
    { id: 4, name: 'Create Ticket', action: 'create_incident', timeout: 30, status: 'pending' },
  ],
  enabled: true,
  hidden: true,
  executions: 0,
  avgTime: '—',
  successRate: 0,
};

export function defaultPlaybooks() {
  return structuredClone([...PLAYBOOKS, MANUAL_PLAYBOOK]);
}
